using System;
using Microsoft.Xna.Framework;
using TheraEngine.Collections;
using TheraEngine.Components;
using TheraEngine.Helpers;

namespace TheraEngine.Assets.Sea
{
	// Token: 0x02000189 RID: 393
	public class AutogeneratedShallows
	{
		// Token: 0x06000A2F RID: 2607 RVA: 0x00032FB8 File Offset: 0x000311B8
		public AutogeneratedShallows(Transform3D {15677}, Vector3[] {15678})
		{
			this.Elements = new Tlist<Transform3D>();
			foreach (Vector3 value in {15678})
			{
				Vector3 vector = value - {15677}.Translation;
				float num = vector.Length();
				vector.Normalize();
				vector *= num + 50f;
				value = {15677}.Translation + vector;
				Tlist<Transform3D> elements = this.Elements;
				Transform3D transform3D = new Transform3D(value * new Vector3(1f, 0f, 1f) - new Vector3(0f, 2f, 0f), new Vector3(0f, Rand.Angle(), 0f), new Vector3(1f));
				elements.Add(transform3D);
			}
		}

		// Token: 0x040007A7 RID: 1959
		public Tlist<Transform3D> Elements;
	}
}
